export const employees = [
  {
    name: '강호연',
    email: 'dustmqaksdltkfrlfdldi@revive.com',
    position1: 'Programmer',
    position2: 'Developer',
    status: 'Online',
    date: '24/05/20',
    profile: 'employees/employee1.svg',
  },
  {
    name: '김수민',
    email: 'ssuminii@revive.com',
    position1: 'Programmer',
    position2: 'Developer',
    status: 'Offline',
    date: '24/05/20',
    profile: 'employees/employee2.svg',
  },
  {
    name: '이동혁',
    email: 'ldh921126@revive.com',
    position1: 'Programmer',
    position2: 'Developer',
    status: 'Offline',
    date: '24/05/20',
    profile: 'employees/employee3.svg',
  },
  {
    name: '이윤환',
    email: 'chzhqly@revive.com',
    position1: 'Programmer',
    position2: 'Developer',
    status: 'Online',
    date: '24/05/20',
    profile: 'employees/employee4.svg',
  },
  {
    name: '최원지',
    email: 'wonjichoe@revive.com',
    position1: 'Programmer',
    position2: 'Developer',
    status: 'Online',
    date: '24/05/20',
    profile: 'employees/employee5.svg',
  },
]
