export const employeeLists = [
  {
    id: '1',
    name: '강호연',
    email: 'dustmqaksdltkfrlfdldi@revive.com',
    position1: 'Programmer',
    position2: 'Developer',
    status: 'Online',
    date: '24/05/20',
    profile: 'images/employee1.svg',
  },
  {
    id: '2',
    name: '김수민',
    email: 'ssuminii@revive.com',
    position1: 'Programmer',
    position2: 'Developer',
    status: 'Offline',
    date: '24/05/20',
    profile: 'images/employee2.svg',
  },
  {
    id: '3',
    name: '이동혁',
    email: 'ldh921126@revive.com',
    position1: 'Programmer',
    position2: 'Developer',
    status: 'Offline',
    date: '24/05/20',
    profile: 'images/employee3.svg',
  },
  {
    id: '4',
    name: '이윤환',
    email: 'chzhqly@revive.com',
    position1: 'Programmer',
    position2: 'Developer',
    status: 'Online',
    date: '24/05/20',
    profile: 'images/employee4.svg',
  },
  {
    id: '5',
    name: '최원지',
    email: 'wonjichoe@revive.com',
    position1: 'Programmer',
    position2: 'Developer',
    status: 'Online',
    date: '24/05/20',
    profile: 'images/employee5.svg',
  },
]
